### ISSUE TITLE
use gcr.io & a bootcamp related bucket

### ISSUE THREAD

**Issue by craigbox** [kubernetes-retired/kubernetes-bootcamp#13]
`--image=docker.io/jocatalin/kubernetes-bootcamp:v1`

This could be hosted on gcr.io, and again not reference jocatalin.

**Comment by jocatalin** [comment]
@pwittrock will create new images on gcr.io and I'll upgrade the commands to use the new path.

**Comment by pwittrock** [comment]
@craigbox Yes that is something we want to do.  Thanks for filing the issue.

**Comment by BenHall** [comment]
Closed by #61

**Comment by craigbox** [comment]
Leaving open until #61 is merged

/remove-lifecycle stale
